---
title: "Deliverables"
page-layout: full
title-block-style: none
toc: false
validate-yaml: false
filters:
  - multibib
csl: apa-by-year.csl
bibliography:
  publications: pubs.bib
  software: software.bib
nocite: |
  @*
---

At UFDS we strive for a variety of types of deliverables that benefit the FIA Program and our students: from software to peer-reviewed publications to dashboards and more. On this page, we showcase some of our deliverables.

## Publications

::: {#refs-publications}
:::


## Software

::: {#refs-software}
:::


## Student Awards

- [Dinan Elsyad (UFDS '23) won Best Video Presentation at the 2023 Electronic Undergraduate Statistics Research Conference](https://statistics.fas.harvard.edu/news/dinan%C2%A0hamdi-elsyad-receives-best-video-presentation-eusr-2023). See her [video presentation here](https://www.causeweb.org/usproc/eusr/2023/posters/elsyad).

-  [Asteria Chilambo (UFDS '22) and Jing Shang (UFDS '22) won Best Video Presentation at the 2023 Electronic Undergraduate Statistics Research Conference](https://statistics.fas.harvard.edu/news/asteria-chilambo-and-jing-shang-receive-best-video-presentation-eusr-conference). See their [video presentation here](https://www.causeweb.org/usproc/eusr/2022/virtual-posters/8).

- [Olek Wojcik (UFDS '20), Paul Nguyen (UFDS '20), and Samuel Olson (UFDS '20) won second place at the 2020 Spring Undergraduate Statistics Project Competition](https://www.causeweb.org/usproc/usresp/2020/spring/winners).

- Maddie Basil (UFDS '19) won Best Video Presentation at the 2019 Electronic Undergraduate Statistics Research Conference. See her [video presentation here](https://www.causeweb.org/usproc/eusrc/2019/virtual-posters/3).


