---
title: "FAQs"
page-layout: full
title-block-style: none
toc: false
---

::: {.callout-note collapse="true" appearance="minimal"}
## Why should I spend my summer conducting research?

We have so many answers that one of us even wrote a [whole article](https://www.tandfonline.com/doi/full/10.1080/10691898.2020.1756542) about this question! Here’s the shortened version:

-   Learning by doing data science: Practicing data science can really help you develop as a data scientist.

-   Communication skills: You will have multiple opportunities to share your work (both in writing and orally) to your peers, your mentors, the stakeholders, and novices. You will receive feedback to help you hone your communication skills.

-   Professional identity and belonging: Research can help strengthen your connection to the discipline of statistics.

-   Graduate school and career preparation/clarity: The experience will demystify what research is and help you decide if you want to pursue an advanced degree. Plus, grad school or not, the tools and skills learned will help prepare you for your professional life after undergrad.

-   And, it is fun: The data are messy! The questions are vague! The answers are unknown! What more could you want?
:::

::: {.callout-note collapse="true" appearance="minimal"}
## Will I get to co-author a publication as part of this research opportunity?

At the start of a project, it is very difficult to predict whether or not it will result in a publication. And, for some projects, a journal article may not be the most useful final product. So, there is no certainty about whether or not your work will be published, but there will be many ways to share your work. For example, the group will present their findings to FIA researchers and will be expected to participate in any relevant campus research presentation events. We will also strongly encourage you to submit the final technical report to the [Undergraduate Statistics Research Project Competition](https://www.causeweb.org/usproc/usresp) and/or a video presentation to the [Electronic Undergraduate Statistics Research Conference (eUSR)](https://www.causeweb.org/usproc/eusrc). One of the 2022 projects won [“Best Video Presentation” at this year’s eUSR](https://statistics.fas.harvard.edu/news/asteria-chilambo-and-jing-shang-receive-best-video-presentation-eusr-conference)! On top of all that, we will also look for relevant statistics and data science conferences for you to share the work.

Deliverables from previous projects have included [journal articles](https://cdnsciencepub.com/doi/pdf/10.1139/cjfr-2024-0149), [peer-reviewed technical reports](https://research.fs.usda.gov/treesearch/63184), [dashboards](https://ncasi-shiny-tools.shinyapps.io/CPAT_Ver2_Demo/), and [software development](https://cran.r-project.org/web/packages/mase/) (links include an example of each).
:::

::: {.callout-note collapse="true" appearance="minimal"}
## What will a typical day look like?

The work will be highly collaborative. We will start most days with a team meeting where everyone presents their progress, discusses issues, and talks through their next steps. For the rest of the day, your time will likely be split between your projects and will be a mix of coding, writing, problem-solving, and dealing with merge conflicts in GitHub.
:::

::: {.callout-note collapse="true" appearance="minimal"}
## What software will we use?

All our work will be done using R/RStudio and git/GitHub. Previous experience with `R` is strongly recommended but previous experience with git is not.
:::

::: {.callout-note collapse="true" appearance="minimal"}
## What prior coursework is required?

The projects will vary in terms of the computational and statistical skills needed, but each research fellow should have prior experience coding in `R` and building statistical models. Useful courses to have taken include an intro stats course, a coding course, and a modeling course. If you haven’t taken these sorts of courses, you are still encouraged to apply but should address your level of proficiency in `R` and your experience with statistical modeling in your application. If you don’t have prior experience in `R` but can code in another language (such as Python), make sure to mention this in your application.  Those who are new to `R` will be expected to learn and use `R` during UFDS.
:::

::: {.callout-note collapse="true" appearance="minimal"}
## Do I need to be a statistics or computer science major to apply?

No! While some of the former UFDS students have been statistics majors, others have majored in other disciplines such as Economics or English. Coming from a different field often brings a very valuable and unique perspective!
:::